language: c++

compiler: gcc

os: linux

dist: xenial

before_install:
  - ls

addons:
  apt:
    packages:
      - curl
      - g++-aarch64-linux-gnu
      - g++-8-aarch64-linux-gnu
      - gcc-8-aarch64-linux-gnu

script:
  - HOSTS="i686-pc-linux-gnu x86_64-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu"
  - CONFIGFLAGS="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST_CFLAGS="-O2 -g"
  - HOST_CXXFLAGS="-O2 -g"
  - HOST_LDFLAGS=-static-libstdc++

install:
  - make -C depends 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master