language: c++

compiler: gcc

os: linux

dist: xenial

before_install:
  - sudo add-apt-repository universe -y
  - sudo apt-get update -q
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install \
    curl g++-aarch64-linux-gnu g++-8-aarch64-linux-gnu gcc-8-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu g++-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf \
    gcc-8-arm-linux-gnueabihf binutils-arm-linux-gnueabihf g++-riscv64-linux-gnu \
    g++-8-riscv64-linux-gnu gcc-8-riscv64-linux-gnu binutils-riscv64-linux-gnu \
    g++-8-multilib gcc-8-multilib binutils-gold git pkg-config autoconf libtool \
    automake bsdmainutils ca-certificates python

env:
  - HOSTS="i686-pc-linux-gnu x86_64-linux-gnu arm-linux-gnueabihf aarch64-linux-gnu"
  - CONFIGFLAGS="--enable-glibc-back-compat --enable-reduce-exports"
  - HOST_CFLAGS="-O2 -g"
  - HOST_CXXFLAGS="-O2 -g"
  - HOST_LDFLAGS=-static-libstdc++

install:
  - make -C depends 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master